name: CI Workflow on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (sesuaikan dengan versi yang dibutuhkan)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # atau sesuaikan dengan versi Node.js yang dibutuhkan
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional, sesuaikan dengan perintah test project Anda)
      - name: Run tests
        run: npm test

      # Step 5: Build project (optional, jika ada proses build)
      - name: Build project
        run: npm run build
